// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#include "NativeObjcOnlyListener.hpp"  // my header
#include "NativeLambdaInterfaceI64String.hpp"

namespace djinni_generated {

NativeObjcOnlyListener::NativeObjcOnlyListener() : ::djinni::JniInterface<::testsuite::ObjcOnlyListener, NativeObjcOnlyListener>() {}

NativeObjcOnlyListener::~NativeObjcOnlyListener() = default;


}  // namespace djinni_generated
