// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "NativeLambdaInterfaceI64Void.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLambdaInterfaceI64Void::NativeLambdaInterfaceI64Void() : ::djinni::JniInterface<::testsuite::LambdaInterfaceI64Void, NativeLambdaInterfaceI64Void>() {}

NativeLambdaInterfaceI64Void::~NativeLambdaInterfaceI64Void() = default;

NativeLambdaInterfaceI64Void::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeLambdaInterfaceI64Void::JavaProxy::~JavaProxy() = default;

void NativeLambdaInterfaceI64Void::JavaProxy::run(int64_t c_param_1) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeLambdaInterfaceI64Void>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_run,
                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_param_1)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
