// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "NativeLambdaInterfaceI64String.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeLambdaInterfaceI64String::NativeLambdaInterfaceI64String() : ::djinni::JniInterface<::testsuite::LambdaInterfaceI64String, NativeLambdaInterfaceI64String>() {}

NativeLambdaInterfaceI64String::~NativeLambdaInterfaceI64String() = default;

NativeLambdaInterfaceI64String::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeLambdaInterfaceI64String::JavaProxy::~JavaProxy() = default;

std::string NativeLambdaInterfaceI64String::JavaProxy::run(int64_t c_param_1) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeLambdaInterfaceI64String>::get();
    auto jret = (jstring)jniEnv->CallObjectMethod(Handle::get().get(), data.method_run,
                                                  ::djinni::get(::djinni::I64::fromCpp(jniEnv, c_param_1)));
    ::djinni::jniExceptionCheck(jniEnv);
    return ::djinni::String::toCpp(jniEnv, jret);
}

}  // namespace djinni_generated
