// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

package com.dropbox.djinni.test;

import java.util.function.Consumer;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**doc */
public  class LambdaInterfaceI64Void {
    private Consumer<Long> actualLambda;
    public LambdaInterfaceI64Void (Consumer<Long> lambda)
    {
        super();
        this.actualLambda = lambda;
    }
    public void run(long param1)
    {
        this.actualLambda.accept(param1);
    }
}
