// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

package com.dropbox.djinni.test;

import java.util.function.BiConsumer;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**doc */
public  class LambdaInterfaceI64StringVoid {
    private BiConsumer<Long, String> actualLambda;
    public LambdaInterfaceI64StringVoid (BiConsumer<Long, String> lambda)
    {
        super();
        this.actualLambda = lambda;
    }
    public void run(long param1, @Nonnull String param2)
    {
        this.actualLambda.accept(param1, param2);
    }
}
