// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

package com.dropbox.djinni.test;

import java.util.function.Consumer;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**doc */
public  class LambdaInterfaceClientReturnedRecordVoid {
    private Consumer<ClientReturnedRecord> actualLambda;
    public LambdaInterfaceClientReturnedRecordVoid (Consumer<ClientReturnedRecord> lambda)
    {
        super();
        this.actualLambda = lambda;
    }
    public void run(@Nonnull ClientReturnedRecord param1)
    {
        this.actualLambda.accept(param1);
    }
}
