// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

package com.dropbox.djinni.test;

import java.util.HashMap;
import java.util.function.BiConsumer;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**doc */
public  class LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid {
    private BiConsumer<ClientReturnedRecord, HashMap<String, String>> actualLambda;
    public LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid (BiConsumer<ClientReturnedRecord, HashMap<String, String>> lambda)
    {
        super();
        this.actualLambda = lambda;
    }
    public void run(@CheckForNull ClientReturnedRecord param1, @Nonnull HashMap<String, String> param2)
    {
        this.actualLambda.accept(param1, param2);
    }
}
