// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

package com.dropbox.djinni.test;

import java.util.HashMap;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.*;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

public abstract class ReverseClientInterface {
    @Nonnull
    public abstract String returnStr();

    @Nonnull
    public abstract String methTakingInterface(@CheckForNull ReverseClientInterface i);

    @Nonnull
    public abstract String methTakingOptionalInterface(@CheckForNull ReverseClientInterface i);

    public abstract void takeLambdaWhichReturnsNothing(@Nonnull Consumer<Long> cb);

    public abstract void takeLambdaWhichReturnsString(@Nonnull Function<Long, String> cb);

    public abstract void takeBinaryLambdaWhichReturnsNothing(@Nonnull BiConsumer<Long, String> cb);

    public abstract void getRecord(long recordId, @Nonnull Consumer<ClientReturnedRecord> completionCallback);

    public abstract void testTypedClasses(long recordId, @Nonnull BiConsumer<ClientReturnedRecord, HashMap<String, String>> completionCallback);

    @CheckForNull
    public static native ReverseClientInterface create();

    private static final class CppProxy extends ReverseClientInterface
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            destroy();
            super.finalize();
        }

        @Override
        public String returnStr()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_returnStr(this.nativeRef);
        }
        private native String native_returnStr(long _nativeRef);

        @Override
        public String methTakingInterface(ReverseClientInterface i)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_methTakingInterface(this.nativeRef, i);
        }
        private native String native_methTakingInterface(long _nativeRef, ReverseClientInterface i);

        @Override
        public String methTakingOptionalInterface(ReverseClientInterface i)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_methTakingOptionalInterface(this.nativeRef, i);
        }
        private native String native_methTakingOptionalInterface(long _nativeRef, ReverseClientInterface i);

        @Override
        public void takeLambdaWhichReturnsNothing(Consumer<Long> cb)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_takeLambdaWhichReturnsNothing(this.nativeRef, new LambdaInterfaceI64Void(cb));
        }
        private native void native_takeLambdaWhichReturnsNothing(long _nativeRef, LambdaInterfaceI64Void cb);

        @Override
        public void takeLambdaWhichReturnsString(Function<Long, String> cb)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_takeLambdaWhichReturnsString(this.nativeRef, new LambdaInterfaceI64String(cb));
        }
        private native void native_takeLambdaWhichReturnsString(long _nativeRef, LambdaInterfaceI64String cb);

        @Override
        public void takeBinaryLambdaWhichReturnsNothing(BiConsumer<Long, String> cb)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_takeBinaryLambdaWhichReturnsNothing(this.nativeRef, new LambdaInterfaceI64StringVoid(cb));
        }
        private native void native_takeBinaryLambdaWhichReturnsNothing(long _nativeRef, LambdaInterfaceI64StringVoid cb);

        @Override
        public void getRecord(long recordId, Consumer<ClientReturnedRecord> completionCallback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_getRecord(this.nativeRef, recordId, new LambdaInterfaceClientReturnedRecordVoid(completionCallback));
        }
        private native void native_getRecord(long _nativeRef, long recordId, LambdaInterfaceClientReturnedRecordVoid completionCallback);

        @Override
        public void testTypedClasses(long recordId, BiConsumer<ClientReturnedRecord, HashMap<String, String>> completionCallback)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            native_testTypedClasses(this.nativeRef, recordId, new LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid(completionCallback));
        }
        private native void native_testTypedClasses(long _nativeRef, long recordId, LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid completionCallback);
    }
}
