// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#pragma once

#include <cstdint>
#include <string>

namespace testsuite {

/**doc */
class LambdaInterfaceI64String {
public:
    virtual ~LambdaInterfaceI64String() {}

    /**doc */
    virtual std::string run(int64_t param_1) = 0;
};

}  // namespace testsuite
