// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#pragma once

#include "../../handwritten-src/cpp/optional.hpp"
#include <string>
#include <unordered_map>

namespace testsuite {

struct ClientReturnedRecord;

/**doc */
class LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid {
public:
    virtual ~LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid() {}

    /**doc */
    virtual void run(const std::experimental::optional<ClientReturnedRecord> & param_1, const std::unordered_map<std::string, std::string> & param_2) = 0;
};

}  // namespace testsuite
