// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#pragma once

#include <cstdint>
#include <string>

namespace testsuite {

/**doc */
class LambdaInterfaceI64StringVoid {
public:
    virtual ~LambdaInterfaceI64StringVoid() {}

    /**doc */
    virtual void run(int64_t param_1, const std::string & param_2) = 0;
};

}  // namespace testsuite
