// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#pragma once

namespace testsuite {

struct ClientReturnedRecord;

/**doc */
class LambdaInterfaceClientReturnedRecordVoid {
public:
    virtual ~LambdaInterfaceClientReturnedRecordVoid() {}

    /**doc */
    virtual void run(const ClientReturnedRecord & param_1) = 0;
};

}  // namespace testsuite
