// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#pragma once

#include <cstdint>

namespace testsuite {

/**doc */
class LambdaInterfaceI64Void {
public:
    virtual ~LambdaInterfaceI64Void() {}

    /**doc */
    virtual void run(int64_t param_1) = 0;
};

}  // namespace testsuite
