// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "lambda_interface_optional_client_returned_record_map_string_string_void.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBLambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid;

namespace djinni_generated {

class LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid
{
public:
    using CppType = std::shared_ptr<::testsuite::LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid>;
    using CppOptType = std::shared_ptr<::testsuite::LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid>;
    using ObjcType = DBLambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid*;

    using Boxed = LambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

