// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#import "DBClientReturnedRecord.h"
#import <Foundation/Foundation.h>


/**doc */
@interface DBLambdaInterfaceOptionalClientReturnedRecordMapStringStringVoid : NSObject

/**doc */
- (void)run:(nullable DBClientReturnedRecord *)param1
     param2:(nonnull NSDictionary<NSString *, NSString *> *)param2;

@end
