// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#import <Foundation/Foundation.h>


/**doc */
@interface DBLambdaInterfaceI64String : NSObject

/**doc */
- (nonnull NSString *)run:(int64_t)param1;

@end
