// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#import "DBLambdaInterfaceI64Void+Private.h"
#import "DBLambdaInterfaceI64Void.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

auto LambdaInterfaceI64Void::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    DJINNI_UNIMPLEMENTED(@"Interface not implementable in any language.");
}

auto LambdaInterfaceI64Void::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    DJINNI_UNIMPLEMENTED(@"Interface not implementable in any language.");
}

}  // namespace djinni_generated
