// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#include "lambda_interface_client_returned_record_void.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBLambdaInterfaceClientReturnedRecordVoid;

namespace djinni_generated {

class LambdaInterfaceClientReturnedRecordVoid
{
public:
    using CppType = std::shared_ptr<::testsuite::LambdaInterfaceClientReturnedRecordVoid>;
    using CppOptType = std::shared_ptr<::testsuite::LambdaInterfaceClientReturnedRecordVoid>;
    using ObjcType = DBLambdaInterfaceClientReturnedRecordVoid*;

    using Boxed = LambdaInterfaceClientReturnedRecordVoid;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

