// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#import <Foundation/Foundation.h>


/**doc */
@interface DBLambdaInterfaceI64Void : NSObject

/**doc */
- (void)run:(int64_t)param1;

@end
