// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#import <Foundation/Foundation.h>


/**doc */
@interface DBLambdaInterfaceI64StringVoid : NSObject

/**doc */
- (void)run:(int64_t)param1
     param2:(nonnull NSString *)param2;

@end
