// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from 

#import "DBClientReturnedRecord.h"
#import <Foundation/Foundation.h>


/**doc */
@interface DBLambdaInterfaceClientReturnedRecordVoid : NSObject

/**doc */
- (void)run:(nonnull DBClientReturnedRecord *)param1;

@end
