// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#import <Foundation/Foundation.h>
@class DBReverseClientInterface;


@interface DBReverseClientInterface : NSObject

- (nonnull NSString *)returnStr;

- (nonnull NSString *)methTakingInterface:(nullable DBReverseClientInterface *)i;

- (nonnull NSString *)methTakingOptionalInterface:(nullable DBReverseClientInterface *)i;

+ (nullable DBReverseClientInterface *)create;

- (void)takeLambdaWhichReturnsNothing:(nonnull void (^)() *)cb;

- (void)takeLambdaWhichReturnsString:(nonnull void (^)() *)cb;

- (void)takeBinaryLambdaWhichReturnsNothing:(nonnull void (^)() *)cb;

@end
