// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#import "DBClientReturnedRecord.h"
#import <Foundation/Foundation.h>
@class DBReverseClientInterface;


@interface DBReverseClientInterface : NSObject

- (nonnull NSString *)returnStr;

- (nonnull NSString *)methTakingInterface:(nullable DBReverseClientInterface *)i;

- (nonnull NSString *)methTakingOptionalInterface:(nullable DBReverseClientInterface *)i;

+ (nullable DBReverseClientInterface *)create;

- (void)takeLambdaWhichReturnsNothing:(nonnull void  (^) (int64_t  arg))cb;

- (void)takeLambdaWhichReturnsString:(nonnull NSString * _Nonnull (^) (int64_t  arg))cb;

- (void)takeBinaryLambdaWhichReturnsNothing:(nonnull void  (^) (int64_t  arg, NSString * _Nonnull arg1))cb;

- (void)getRecord:(int64_t)recordId
completionCallback:(nonnull void  (^) (DBClientReturnedRecord * _Nonnull clientReturnedRecord))completionCallback;

@end
